### ISSUE TITLE
Migrate to librechat.yaml

### ISSUE THREAD

**Issue by rudolfjs** [rudolfjs/librechat-deploy#1]
## Issue

Currently using the `.env` file for managing the Librechat deployment.  Create an example `.yaml` file and migrate the configuration to `librechat.yaml`.

In docker, change the config to:

```yaml
services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
```
